language: go

go_import_path: gopkg.in/src-d/go-errors.v1

go:
    - 1.11
    - 1.12

install:
  - go get -v -t ./...

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - name: 'Go Modules'
      install:
      script:
        - GO111MODULE=on make test
